version: "3.8"

services:
  postgres_ylab:
    container_name: postgres_ylab
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - PGUSER=postgres
    ports:
      - "${LOCAL_POSTGRES_PORT:-5432}:5432"
    networks:
      - ylab_network
    healthcheck:
      test: sh -c "pg_isready -U ${POSTGRES_USER:?err} -d ${POSTGRES_DB:?err}"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  redis_ylab:
    container_name: redis_ylab
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data
    ports:
      - "${LOCAL_REDIS_PORT:-6379}:6379"
    networks:
      - ylab_network
    healthcheck:
      test: sh -c "redis-cli ping"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  fastapi_ylab:
    container_name: fastapi_ylab
    build:
      context: .
      dockerfile: ./core/Dockerfile
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_HOST=postgres_ylab
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis_ylab
      - REDIS_PORT=6379
    entrypoint: sh -c "alembic upgrade head && uvicorn core.main:app --host 0.0.0.0 --port 80"
    volumes:
      - shared-volume:/core/generated_files
    ports:
      - "${LOCAL_FASTAPI_PORT:-80}:80"
    networks:
      - ylab_network
    depends_on:
      postgres_ylab:
        condition: service_healthy
      redis_ylab:
        condition: service_healthy
    healthcheck:
      test: curl localhost:80/api/v1/menus || exit 1
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  rabbitmq_ylab:
    container_name: rabbitmq_ylab
    image: rabbitmq:3.12-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "${LOCAL_RABBIT_PORT:-5672}:5672"
      - "${LOCAL_RABBIT_GUI_PORT:-15672}:15672"
    networks:
      - ylab_network
    healthcheck:
      test: sh -c "rabbitmq-diagnostics -q ping"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  celery_worker_ylab:
    container_name: celery_worker_ylab
    build:
      context: .
      dockerfile: ./celery_app/Dockerfile
    environment:
      - FASTAPI_HOST=fastapi_ylab
      - FASTAPI_PORT=80
      - RABBIT_HOST=rabbitmq_ylab
      - RABBIT_PORT=5672
    entrypoint: sh -c "celery -A celery_app.tasks worker --loglevel=INFO"
    volumes:
      - celery_worker_data:/data
    networks:
      - ylab_network
    depends_on:
      fastapi_ylab:
        condition: service_healthy
      rabbitmq_ylab:
        condition: service_healthy

  celery_beat_ylab:
    container_name: celery_beat_ylab
    build:
      context: .
      dockerfile: ./celery_app/Dockerfile
    environment:
      - FASTAPI_HOST=fastapi_ylab
      - FASTAPI_PORT=80
      - RABBIT_HOST=rabbitmq_ylab
      - RABBIT_PORT=5672
    entrypoint: sh -c "celery -A celery_app.tasks beat --loglevel=INFO"
    volumes:
      - celery_beat_data:/data
    networks:
      - ylab_network
    depends_on:
      fastapi_ylab:
        condition: service_healthy
      rabbitmq_ylab:
        condition: service_healthy

networks:
  ylab_network:
    name: ylab_network

volumes:
  postgres_data:
  shared-volume:
  redis_data:
  rabbitmq_data:
  celery_worker_data:
  celery_beat_data:
